### ISSUE TITLE
Problema no método connect()

### ISSUE THREAD

**Issue by eduardofaneli** [wgalleti/pyDbOracle#2]
por passar um dict vazio, quando tenta realizar a conexão sem passar o parâmetro "encoding" retorna erro: 'NoneType' object is not a mapping
self.options = dict() 

necessário passar encoding na string de conexão. Exemplo:
`oracle://sigam:sigam@666.66.66.666:1521/orlihmg?encoding=utf-8`

**Comment by wgalleti** [comment]
Realmente foi necessário colocar os options para implementar a parte de encoding, threaded (RAC), porém, faltou deixar um parametro default caso não fosse informado algo.

Corrigi isso no commit 72f8ba7226d849b2f19db4ef28a5fb65e84dd1a2
